version: "2.1"
services:
  javsp:
    image: javsp_image:latest
    container_name: javsp
    environment:
      - PUID=${PUID}    # 填写自己要指定的，不指定可以删除
      - PGID=${PGID}    # 填写自己要指定的，不指定可以删除
      - TZ=${TZ}        # 填写自己要指定的，不指定可以删除
    volumes:
      - ${media_disk}/pool/video:/video   # 映射存放影片的目录
    ports:
      - 8501:8501                              
    restart: always
